In [3]:
from daily3.models import iresult, idraw, idraw_c
from daily3.fetcher import Fetcher

class Daily3:
    DF_RESULTS = {}
    DF_RESULTS = {}
    
    def __init__(self):
        pass;
    
    def fetch_online_results(self):
        f = Fether();
        df_res = f.fetch_results();
        
    def derive_draws(self):
        results = iresult.iResult().db.session.query(iresult.iResult).all();
        for result in results:
            #print(result.draw_id, result.r);
            dr = idraw.iDraw(result.draw_id, result.r);
            #dr.derive();
            #print(dr.toString())
            dr.db_save()
            
    def derive_draws_c(self):
        results = iresult.iResult().db.session.query(iresult.iResult).all();
        for result in results:
            dr = idraw_c.iDrawC(result.draw_id, result.r);
            dr.db_save()
            
    def get_draws_df(self):
        return idraw.iDraw().get_dataframe();
    
    def get_results_df(self):
        return iresult.iResult().get_dataframe();
    
    def get_master_df(self):
        r_df = self.get_results_df()
        r_df.set_index('draw_id', inplace=True);
        dr_df = self.get_draws_df()
        dr_df.set_index('draw_id', inplace=True);
        master_df = r_df.join(dr_df, on='draw_id');
        return master_df;
    
    def export_dfs(self):
        r_df = self.get_results_df()
        r_df.set_index('draw_id', inplace=True);
        r_df.to_pickle('data/daily3/master/daily3_master_r.pkl')
        
        dr_df = self.get_draws_df()
        dr_df.set_index('draw_id', inplace=True);        
        dr_df.to_pickle('data/daily3/master/daily3_master_dr.pkl')
        
        master_df = r_df.join(dr_df, on='draw_id');        
        master_df.to_pickle('data/daily3/master/daily3_master.pkl')
        
        ids_df = pd.DataFrame(r_df.index)
        ids_df.set_index('draw_id', inplace=True)
        ids_df.to_pickle('data/daily3/master/daily3_master_ids.pkl')

In [4]:
d3 = Daily3()
d3.derive_draws_c()

In [5]:
import pandas as pd
ids_df = pd.read_pickle('data/daily3/master/daily3_master_dr.pkl')
ids_df

,p1n0,p1n1,p1n2,p1n3,p1n4,p1n5,p1n6,p1n7,p1n8,p1n9,...,p3n0,p3n1,p3n2,p3n3,p3n4,p3n5,p3n6,p3n7,p3n8,p3n9
draw_id,,,,,,,,,,,,,,,,,,,,,
16016,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
16017,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
16018,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
16019,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
16020,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16746,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
16747,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16748,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
16749,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
16750,0,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0